# Generated by Django 6.0.2 on 2026-02-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
